"""Add llm settings

Revision ID: 5bf9cc52ef96
Revises: ddf1d9fc2b6f
Create Date: 2025-10-25 22:37:38.107818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf9cc52ef96'
down_revision: Union[str, Sequence[str], None] = 'ddf1d9fc2b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'temperature', name='_model_temperature_uc')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcription_settings_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('persona_settings_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('feedback_settings_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_settings_feedback_settings', 'llm_settings', ['feedback_settings_id'], ['id'])
        batch_op.create_foreign_key('fk_settings_transcription_settings', 'llm_settings', ['transcription_settings_id'], ['id'])
        batch_op.create_foreign_key('fk_settings_persona_settings', 'llm_settings', ['persona_settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_settings_persona_settings', type_='foreignkey')
        batch_op.drop_constraint('fk_settings_transcription_settings', type_='foreignkey')
        batch_op.drop_constraint('fk_settings_feedback_settings', type_='foreignkey')
        batch_op.drop_column('feedback_settings_id')
        batch_op.drop_column('persona_settings_id')
        batch_op.drop_column('transcription_settings_id')
    op.drop_table('llm_settings')
    # ### end Alembic commands ###