"""Add settings model

Revision ID: aa8bcff43cd3
Revises: 
Create Date: 2025-10-20 15:53:29.886373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8bcff43cd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gemini_api_key', sa.String(), nullable=True),
    sa.Column('elevenlabs_api_key', sa.String(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('evaluation_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
