"""Attach persona to language profile

Revision ID: bb6f7ab73caa
Revises: bdfed1bc9799
Create Date: 2025-10-25 09:56:27.322170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6f7ab73caa'
down_revision: Union[str, Sequence[str], None] = 'bdfed1bc9799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_language_profiles_persona_id'), ['persona_id'], unique=False)
        batch_op.create_foreign_key('fk_language_profiles_persona_id', 'personas', ['persona_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_language_profiles_persona_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_language_profiles_persona_id'))
        batch_op.drop_column('persona_id')
    # ### end Alembic commands ###