"""Add language profiles models

Revision ID: bdfed1bc9799
Revises: d05fba3d55d6
Create Date: 2025-10-21 09:50:38.521348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfed1bc9799'
down_revision: Union[str, Sequence[str], None] = 'd05fba3d55d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_profiles_id'), 'language_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_language_profiles_name'), 'language_profiles', ['name'], unique=False)
    op.create_table('practice_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_profile_id'], ['language_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_topics_id'), 'practice_topics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_topics_id'), table_name='practice_topics')
    op.drop_table('practice_topics')
    op.drop_index(op.f('ix_language_profiles_name'), table_name='language_profiles')
    op.drop_index(op.f('ix_language_profiles_id'), table_name='language_profiles')
    op.drop_table('language_profiles')
    # ### end Alembic commands ###
