"""Ad feedback language field

Revision ID: ddf1d9fc2b6f
Revises: bb6f7ab73caa
Create Date: 2025-10-25 10:45:57.560607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf1d9fc2b6f'
down_revision: Union[str, Sequence[str], None] = 'bb6f7ab73caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('feedback_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'feedback_language')
    # ### end Alembic commands ###
